// Writes the package sources generated from Yeti's build at the pin (setup
// spec sections 1 and 3; ADR 0060 points 3 and 10): `yeti-types.ts`, a copy
// of `dist/yeti.d.ts`, and `yeti-rank.ts`, the 49 items in the import order of
// `dist/css/yeti.css` with the pin. Run it through `npx nx yeti-sources
// ngx-yeti`, which builds Yeti first. Its outputs are committed.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { format, resolveConfig } from 'prettier';

const workspaceRoot = join(import.meta.dirname, '../..');
const yetiRoot = join(workspaceRoot, 'vendor/yeti');
const packageRoot = join(workspaceRoot, 'packages/ngx-yeti');

/** Yeti's folder for each kind, as `YetiKind` names the kind. */
const kinds = {
  layouts: 'layout',
  recipes: 'recipe',
  components: 'component',
  utilities: 'utility',
};

const pin = readFileSync(join(yetiRoot, 'COMMIT'), 'utf8').trim();
const entryStylesheet = readFileSync(
  join(yetiRoot, 'dist/css/yeti.css'),
  'utf8',
);
const items = [
  ...entryStylesheet.matchAll(/@import "(([\w-]+)\/([\w-]+)\/\3\.css)";/g),
].map(([, path, folder, name]) => {
  const kind = kinds[folder];

  if (kind === undefined) {
    throw new Error(`Unknown Yeti folder "${folder}" in ${path}`);
  }

  return { name, kind, path };
});

if (!/^[0-9a-f]{40}$/.test(pin)) {
  throw new Error(`vendor/yeti/COMMIT is not a full sha: "${pin}"`);
}

if (items.length !== 49) {
  throw new Error(`Expected 49 items in yeti.css, found ${items.length}`);
}

writeFileSync(
  join(packageRoot, 'src/yeti-types.ts'),
  readFileSync(join(yetiRoot, 'dist/yeti.d.ts')),
);

const rankPath = join(packageRoot, 'styles/src/yeti-rank.ts');
const rankSource = `// Generated by tools/yeti/generate-sources.mjs from Yeti's dist/css/yeti.css
// at the pin. Do not edit; run \`npx nx yeti-sources ngx-yeti\` after a pin move.
import type { YetiComponentName, YetiKind } from 'ngx-yeti';

/** The full sha of the Yeti commit the package is built against. */
export const yetiPin = '${pin}';

/** One item file of Yeti's build. */
export interface YetiRankEntry {
  /** The item's place in \`yeti.css\`'s import order, from 0. */
  readonly rank: number;
  readonly kind: YetiKind;
  /** The file's path under Yeti's \`dist/css/\`. */
  readonly path: string;
}

/** Yeti's 49 item files in \`yeti.css\`'s import order. */
export const yetiRank = {
${items
  .map(
    ({ name, kind, path }, rank) =>
      `  '${name}': { rank: ${rank}, kind: '${kind}', path: '${path}' },`,
  )
  .join('\n')}
} as const satisfies Record<YetiComponentName, YetiRankEntry>;
`;

writeFileSync(
  rankPath,
  await format(rankSource, {
    ...(await resolveConfig(rankPath)),
    filepath: rankPath,
  }),
);
