// Generated by tools/yeti/generate-sources.mjs from Yeti's dist/css/yeti.css
// at the pin. Do not edit; run `npx nx yeti-sources ngx-yeti` after a pin move.
import type { YetiComponentName, YetiKind } from 'ngx-yeti';

/** The full sha of the Yeti commit the package is built against. */
export const yetiPin = 'f52d1e8b93de5bbde322480ba77d5be26c49b0ef';

/** One item file of Yeti's build. */
export interface YetiRankEntry {
  /** The item's place in `yeti.css`'s import order, from 0. */
  readonly rank: number;
  readonly kind: YetiKind;
  /** The file's path under Yeti's `dist/css/`. */
  readonly path: string;
}

/** Yeti's 49 item files in `yeti.css`'s import order. */
export const yetiRank = {
  stack: { rank: 0, kind: 'layout', path: 'layouts/stack/stack.css' },
  cluster: { rank: 1, kind: 'layout', path: 'layouts/cluster/cluster.css' },
  sidebar: { rank: 2, kind: 'layout', path: 'layouts/sidebar/sidebar.css' },
  columns: { rank: 3, kind: 'layout', path: 'layouts/columns/columns.css' },
  cover: { rank: 4, kind: 'layout', path: 'layouts/cover/cover.css' },
  grid: { rank: 5, kind: 'layout', path: 'layouts/grid/grid.css' },
  frame: { rank: 6, kind: 'layout', path: 'layouts/frame/frame.css' },
  scroller: { rank: 7, kind: 'layout', path: 'layouts/scroller/scroller.css' },
  overlay: { rank: 8, kind: 'layout', path: 'layouts/overlay/overlay.css' },
  box: { rank: 9, kind: 'layout', path: 'layouts/box/box.css' },
  center: { rank: 10, kind: 'layout', path: 'layouts/center/center.css' },
  icon: { rank: 11, kind: 'layout', path: 'layouts/icon/icon.css' },
  masonry: { rank: 12, kind: 'layout', path: 'layouts/masonry/masonry.css' },
  breakout: { rank: 13, kind: 'layout', path: 'layouts/breakout/breakout.css' },
  layer: { rank: 14, kind: 'layout', path: 'layouts/layer/layer.css' },
  container: {
    rank: 15,
    kind: 'layout',
    path: 'layouts/container/container.css',
  },
  timeline: { rank: 16, kind: 'layout', path: 'layouts/timeline/timeline.css' },
  media: { rank: 17, kind: 'recipe', path: 'recipes/media/media.css' },
  hero: { rank: 18, kind: 'recipe', path: 'recipes/hero/hero.css' },
  shell: { rank: 19, kind: 'recipe', path: 'recipes/shell/shell.css' },
  button: { rank: 20, kind: 'component', path: 'components/button/button.css' },
  buttons: {
    rank: 21,
    kind: 'component',
    path: 'components/buttons/buttons.css',
  },
  badge: { rank: 22, kind: 'component', path: 'components/badge/badge.css' },
  card: { rank: 23, kind: 'component', path: 'components/card/card.css' },
  field: { rank: 24, kind: 'component', path: 'components/field/field.css' },
  affix: { rank: 25, kind: 'component', path: 'components/affix/affix.css' },
  table: { rank: 26, kind: 'component', path: 'components/table/table.css' },
  seam: { rank: 27, kind: 'component', path: 'components/seam/seam.css' },
  nav: { rank: 28, kind: 'component', path: 'components/nav/nav.css' },
  breadcrumbs: {
    rank: 29,
    kind: 'component',
    path: 'components/breadcrumbs/breadcrumbs.css',
  },
  pagination: {
    rank: 30,
    kind: 'component',
    path: 'components/pagination/pagination.css',
  },
  toc: { rank: 31, kind: 'component', path: 'components/toc/toc.css' },
  alert: { rank: 32, kind: 'component', path: 'components/alert/alert.css' },
  progress: {
    rank: 33,
    kind: 'component',
    path: 'components/progress/progress.css',
  },
  spinner: {
    rank: 34,
    kind: 'component',
    path: 'components/spinner/spinner.css',
  },
  accordion: {
    rank: 35,
    kind: 'component',
    path: 'components/accordion/accordion.css',
  },
  tabs: { rank: 36, kind: 'component', path: 'components/tabs/tabs.css' },
  dropdown: {
    rank: 37,
    kind: 'component',
    path: 'components/dropdown/dropdown.css',
  },
  dialog: { rank: 38, kind: 'component', path: 'components/dialog/dialog.css' },
  tooltip: {
    rank: 39,
    kind: 'component',
    path: 'components/tooltip/tooltip.css',
  },
  carousel: {
    rank: 40,
    kind: 'component',
    path: 'components/carousel/carousel.css',
  },
  demo: { rank: 41, kind: 'component', path: 'components/demo/demo.css' },
  attention: {
    rank: 42,
    kind: 'utility',
    path: 'utilities/attention/attention.css',
  },
  billboard: {
    rank: 43,
    kind: 'utility',
    path: 'utilities/billboard/billboard.css',
  },
  enter: { rank: 44, kind: 'utility', path: 'utilities/enter/enter.css' },
  lede: { rank: 45, kind: 'utility', path: 'utilities/lede/lede.css' },
  lift: { rank: 46, kind: 'utility', path: 'utilities/lift/lift.css' },
  print: { rank: 47, kind: 'utility', path: 'utilities/print/print.css' },
  'visually-hidden': {
    rank: 48,
    kind: 'utility',
    path: 'utilities/visually-hidden/visually-hidden.css',
  },
} as const satisfies Record<YetiComponentName, YetiRankEntry>;
